#!/usr/bin/env sh
":" ; pushd "$(dirname ${0})"; emacs -Q --script "$(basename ${0})" -- "${@}"; exit ${?} # -*- emacs-lisp -*-
;;; build.el --- Build script for Org-made documents -*- lexical-binding: t; -*-

;; Copyright (C) 2026 Sidney PEPO

;; Author: Sidney PEPO <sidneypepo@disroot.org>

;; Version: 20260622
;; Keywords: webpage, curriculum vitae, cv, resume

;; This file is not part of GNU Emacs.

;; This program is free software: you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program. If not, see <http://www.gnu.org/licenses/>.

;;; Commentary:

;; Script for building Org-made webpages, Curriculum Vitaes, resumes and other
;; related academic/professional documents

;;; Code:

(message "[*] Initializing build environment...")

(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(package-initialize)

(unless (> (string-to-number emacs-version) 29.0)
  (unless (package-installed-p 'use-package)
    (package-refresh-contents)
    (package-install 'use-package)))

(require 'use-package-ensure)
(setq use-package-always-ensure t)

(use-package ox
  :ensure nil)
(use-package ox-html
  :ensure nil)
(use-package ox-latex
  :ensure nil)
(use-package ox-publish
  :ensure nil)

(use-package org
  :custom
  (org-export-with-sub-superscripts '{})

  :config
  (defun html-export-filters (output backend info)
    "Remove metadata comments generated by Org."
    (when (eq backend 'html)
      (replace-regexp-in-string
       "^[[:space:]]*<!--  -->\n" ""
       (replace-regexp-in-string
	" id=\"[[:alpha:]-]*org[[:alnum:]]\\{7\\}\"" "" output t) t)))
  (add-to-list 'org-export-filter-final-output-functions 'html-export-filters)

  (add-to-list 'org-publish-project-alist
	       '("www"
		 :base-directory "."
		 :publishing-directory "."
		 :base-extension "org"
		 :recursive t
		 :publishing-function org-html-publish-to-html

		 :author ""
		 :html-doctype "html5"
		 :html-head "<meta name=\"color-scheme\" content=\"dark light\">
<link rel=\"stylesheet\" href=\"https://www.sidneypepo.com/assets/css/style.css\" type=\"text/css\"/>"
		 :html-head-include-default-style nil
		 :html-html5-fancy t
		 :html-indent t
		 :html-metadata-timestamp-format ""
		 :html-postamble nil
		 :html-toplevel-hlevel 1
		 :section-numbers nil
		 :with-creator nil
		 :with-date nil
		 :with-special-strings nil
		 :with-statistics-cookies nil
		 :with-toc nil
		 :with-title nil)))

(message "[*] Starting build...")

(org-publish "www")

(message "[+] Build finished!")

;;; build.el ends here
